### ISSUE TITLE
No level geometry

### ISSUE THREAD

**Issue by butterbutts** [cipherxof/Haven#3]
I'm using Solideye to unpack the stage files, but I don't get any level geometry, only a couple of objects or sometimes nothing at all.
Is there some other way I'm supposed to be unpacking the stages?
![Screenshot 2024-02-18 201312](https://github.com/cipherxof/Haven/assets/74153014/26b8e633-c108-446b-890a-0dc824e12a89)

**Comment by cipherxof** [comment]
I'm assuming this is for MGS4?

Most of the geom files in MGS4's stage directory only contain props or references. The geoms with most of the collision data will be in the .slot files.

**Comment by butterbutts** [comment]
Yes, for MGS4. And thank you that helps a lot.
If you don't mind though, what I'm trying to do is export a stage into blender. The export to PLY option doesn't import, Blender throws an unknown error, and other model viewers like Noesis can't read it either. Is there any other way to export the geometry? And can the textures be extracted too?
